name: Crystal CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: "*"

jobs:
  check_spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Spelling
        uses: crate-ci/typos@v1.16.20
  check_format:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Format
        run: crystal tool format --check
  # coding_standards:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: crystallang/crystal:latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Install Dependencies
  #       run: shards install
  #       env:
  #         SHARDS_OVERRIDE: shard.dev.yml
  #     - name: Ameba
  #       run: ./bin/ameba
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          # - windows-latest
        crystal:
          - 1.6.2
          - latest
          - nightly
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{matrix.crystal}}
      - name: Install dependencies
        run: shards install --skip-postinstall --skip-executables
      - name: Run specs
        run: crystal spec
